# Generated by Django 4.2.2 on 2025-05-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetailData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Market', models.CharField(max_length=100)),
                ('Channel', models.CharField(max_length=100)),
                ('Region', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('SubCategory', models.CharField(max_length=100)),
                ('Brand', models.CharField(max_length=100)),
                ('Variant', models.CharField(max_length=100)),
                ('PackType', models.CharField(max_length=100)),
                ('PPG', models.CharField(max_length=100)),
                ('PackSize', models.CharField(max_length=50)),
                ('Year', models.IntegerField()),
                ('Month', models.IntegerField()),
                ('Week', models.IntegerField()),
                ('Date', models.DateField()),
                ('BrCatId', models.CharField(max_length=100)),
                ('SalesValue', models.FloatField()),
                ('Volume', models.FloatField()),
                ('VolumeUnits', models.CharField(max_length=50)),
                ('D1', models.FloatField(blank=True, null=True)),
                ('D2', models.FloatField(blank=True, null=True)),
                ('D3', models.FloatField(blank=True, null=True)),
                ('D4', models.FloatField(blank=True, null=True)),
                ('D5', models.FloatField(blank=True, null=True)),
                ('D6', models.FloatField(blank=True, null=True)),
                ('AV1', models.FloatField(blank=True, null=True)),
                ('AV2', models.FloatField(blank=True, null=True)),
                ('AV3', models.FloatField(blank=True, null=True)),
                ('AV4', models.FloatField(blank=True, null=True)),
                ('AV5', models.FloatField(blank=True, null=True)),
                ('AV6', models.FloatField(blank=True, null=True)),
                ('EV1', models.FloatField(blank=True, null=True)),
                ('EV2', models.FloatField(blank=True, null=True)),
                ('EV3', models.FloatField(blank=True, null=True)),
                ('EV4', models.FloatField(blank=True, null=True)),
                ('EV5', models.FloatField(blank=True, null=True)),
                ('EV6', models.FloatField(blank=True, null=True)),
                ('PrepDate', models.DateField()),
            ],
        ),
    ]
